seo:
  site_name: Example
  title: Example SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url:
  facebook_url:
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#2e2e2e'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#C4907F'
  medium_color: '#A3AD9A'
  light_color: '#F5EBDE'
  v-light_color: '#f9f9f9'
  featured_color: '#6495ed'
  accent_color: '#a74a4a'
