seo:
  site_name: Rain & Rosemary
  title: Rain & Rosemary
  description:
  keywords:
  social_image: /images/index/index-banner.jpg
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/lluvia_magdalena_/
  facebook_url: https://www.facebook.com/jule.bambule.7
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#2e2e2e'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#c4907f'
  medium_color: '#a3ad9a'
  light_color: '#f5ebde'
  v-light_color: '#f9f9f9'
  featured_color: '#606060'
  accent_color: '#a74a4a'
